var namespacesonia__common__py_1_1execptions_1_1sonia__common__exception =
[
    [ "SoniaCommonException", "d8/d1e/classsonia__common__py_1_1execptions_1_1sonia__common__exception_1_1_sonia_common_exception.html", "d8/d1e/classsonia__common__py_1_1execptions_1_1sonia__common__exception_1_1_sonia_common_exception" ]
];