uint8 ELEMENT_TORPEDO = 0
uint8 ELEMENT_DROPPER = 1

uint8 SIDE_PORT = 0
uint8 SIDE_STARBOARD = 1

uint8 ACTION_RESET = 0
uint8 ACTION_LAUNCH = 1

uint8 element
uint8 side
uint8 action
---
bool success