#Name of classe
string class_name

#Prediction confidence
float32 confidence

#Distance to object
float64 distance

#Angle to align
float64 angle_alpha
float64 angle_teta
float64 distance_teta

#ID of the frame
string frame_id

# 2D bounding box surrounding the object.
float64 top_left_x
float64 top_left_y
float64 top_right_x
float64 top_right_y
float64 bottom_left_x
float64 bottom_left_y
float64 bottom_right_x
float64 bottom_right_y
