name: Build

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

on:
  pull_request:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-docker-action@v4
      - uses: actions/checkout@v4
        with:
          repository: sonia-auv/docker_ci 
          # TODO: Should be changed to develop
          ref: build_sonia_bt_runner_and_common
      - name: Running
        run: |
          ./scripts/ci.sh sonia_common_ros2 $BRANCH_NAME
